language: ruby
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
addons:
  postgresql: "9.4"
before_install:
  - gem update --system
  - gem --version
  - gem install -v 2.1.4 bundler
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
cache: bundler
gemfile:
  - gemfiles/activerecord_5.0.0.gemfile
  - gemfiles/activerecord_5.1.0.gemfile
